## Day_5 Practice

In [37]:
# empty list
lst=[]

# list declaration
name = ['saheed','adewoye', 'damilola','adam','abdulloh']
print(len(name))
print(name[0], name [2], name[-1])

mixed_data_types = ['saheed', 350, 5.44, 'single', 'ilorin']

# lsits modification
it_companies = ['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon']
print(it_companies)
print(it_companies[0], it_companies [3], it_companies[-1])

it_companies[3]= 'open AI'
print(it_companies)

it_companies.append('huawei')
it_companies.insert(4,'honor')
it_companies[4]=it_companies[4].upper()  # changing honor to capital
print(it_companies)
it_companies.extend('#')            # joining with #
print('HONOR' in it_companies)      # Checking if a honor company exists
it_companies.sort()
it_companies.sort(reverse=True)
print(it_companies)

# slicing

print(it_companies[:3])        # slicing out the first three company from the list
print(it_companies[-3:])       # slicing out the last three company from the list
print(it_companies[4:6])       # slicing out the middle companies
it_companies.pop(0)            # removing the first company
it_companies.remove('IBM')     # removing the middle company
it_companies.pop(-1)           # removing the last company

print(it_companies)

del it_companies

print(it_companies)

5
saheed damilola abdulloh
['Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon']
Facebook Apple Amazon
['Facebook', 'Google', 'Microsoft', 'open AI', 'IBM', 'Oracle', 'Amazon']
['Facebook', 'Google', 'Microsoft', 'open AI', 'HONOR', 'IBM', 'Oracle', 'Amazon', 'huawei']
True
['open AI', 'huawei', 'Oracle', 'Microsoft', 'IBM', 'HONOR', 'Google', 'Facebook', 'Amazon', '#']
['open AI', 'huawei', 'Oracle']
['Facebook', 'Amazon', '#']
['IBM', 'HONOR']
['huawei', 'Oracle', 'Microsoft', 'HONOR', 'Google', 'Facebook', 'Amazon']

NameError: name 'it_companies' is not defined

In [46]:
# joining of list

front_end = ['HTML', 'CSS', 'JS', 'React', 'Redux']
back_end = ['Node','Express', 'MongoDB']

full_stack = front_end + back_end
full_stack.insert(5,'Python')
full_stack.insert(6,'SQL')
print(full_stack)

['HTML', 'CSS', 'JS', 'React', 'Redux', 'Python', 'SQL', 'Node', 'Express', 'MongoDB']

In [11]:

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]

ages.sort()      # after sorting the minimum age is 19 & the maximum is 26

max = ages[-1]   # the max number in the list
min = ages[0]    # the min number in the list

min_max = [19,26]
ages.extend(min_max)  # adding the min and max age to the list
ages.sort() 
print(ages)

# medium
mid = len(ages) //2
rem = (ages[mid] + ages[~mid]) / 2

print ('the median of the list is ',rem)

# average sum
avg = sum(ages) / len(ages)
print(avg)

# range
range = max - min
print(r)

# comparing (min-average), (max-average) using abs()
min_avg = abs (min -avg)
max_avg = abs(max - avg)

print(min_avg)
print(max_avg)

[19, 19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26]
the median of the list is  24.0
22.75
7
3.75
3.25

In [91]:
# dividing countries into two

countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombi',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor (Timor Timur)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia, The',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]


two = len(countries) / 2

first_half = countries[:97]
second_half = countries[97:]

print(len(first_half))
print(len(second_half))

97
96

In [97]:
# unpacking list items

county = ['China', 'Russia', 'USA', 'Finland', 'Sweden', 'Norway', 'Denmark']

mn,ff,ee, *scandic = county

print(mn,ff,ee)
print(scandic)

China Russia USA
['Finland', 'Sweden', 'Norway', 'Denmark']